### ISSUE TITLE
[Bug] WiFiMenuItemView changes its width mysteriously and RANDOMLY when a random key is pressed

### ISSUE THREAD

**Issue by williambj1** [zxystd/HeliPort#23]
### Describe the bug
WiFiMenuItemView changes its width ***RANDOMLY*** when a random key is pressed on the keyboard, icons are shifted to the left and the highlightable width is reduced. Both the normal and the advanced menu are affected.

### To Reproduce
1. Open the menu
2. Press any key
3. BOOOM

#### NOTE:

**This bug is only reproducible when:**

- You first built the app and didn't touch any part of the code
- Or: You changed some code and left the app running in the background for some time

**This bug mysteriously disappears when:**
- You added a `print` in WiFiMenuItemView.swift and immediately launched the app
- You cleared the logs in Xcode's console
- (under both conditions, leaving the app in the background will make this bug appear again)

### Expected behavior
No mystery width changes

### Video:
*[Watch this](https://github.com/zxystd/HeliPort/files/4808134/bug.zip)*

### Environment (please complete the following information):
 - OS Version: macOS 10.15.4 (19E287)
 - Software Version: commit d9edce3

### Additional context
```draw()``` gets called randomly when any key is pressed, sometimes it will, sometimes it won't, once the key triggers ```draw()```, the menu size gets reduced.
**WTF APPLE???**

**Comment by ErrorErrorError** [comment]
In my case I started seeing this issue when I added "Wi-Fi : Looking for Networks...". Every time it changes the text it changes the width of the  view. I was unable to get the issue when I tried to reproduce the steps you did. Seems to be something with the superview changing bounds.

**Comment by ErrorErrorError** [comment]
Based on my testing, a way to "fix" this issue is by setting the frame's width of the WiFiMenuItemView to 285, which is from the minimumWidth of StatusBar, however that will rule out the autoresizingMask.

Is there any reason to have autoresizingMask for the WiFiMenuItemView itself? Is it supposed to follow superview's width or increase the width only if the SSID name is longer, thus it resizes the whole NSMenu?
