### ISSUE TITLE
 提个建议：wifi图标点击之后。

### ISSUE THREAD

**Issue by AndromedaX7** [zxystd/HeliPort#32]
1. Wi-Fi按钮点击之后，lookingfor network 位置建议显示当前连接的wifi。（时间长了不知道介入的wifi是什么）。**建议显示为 WI-FI：Wi-Fi名字 显示字体颜色为黑色。** 否则会认为灰色是不可用的
2. **记住密码功能建议实现**。
3. 默认wifi连接后建议图标变成连接状态。（有时自动连接驱动设置的wifi图标是灰色的）

**Comment by williambj1** [comment]
1. 苹果没有这么做，我们也没必要这么做，打个勾就好了
2. 看 pr #30 
3. 代码没写完
