### ISSUE TITLE
Is it possible to support lower versions of Swift 4.1？

### ISSUE THREAD

**Issue by kai2ou** [zxystd/HeliPort#9]
macOS 10.13, Xcode 9.4.1 Compilation failure.
`The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`

**Comment by williambj1** [comment]
Swift changes it's syntax in every version and it's not backward capable.
However, compiled binary files work fine in lower macOS versions.

Consider upgrading to a newer macOS and Xcode.

**Comment by kai2ou** [comment]
> However, compiled binary files work fine in lower macOS versions.

Replace the default macos deployment target 10.15 with 10.13?
So that macos 10.13 can use the app.

**Comment by williambj1** [comment]
Sure
